---
- name: Adicionando o master ao cluster k8s
  shell:
    kubeadm join --token={{ hostvars['K8S_TOKEN_HOLDER']['token'] }} 
    --discovery-token-ca-cert-hash sha256:{{ hostvars['K8S_TOKEN_HOLDER']['hash'] }} 
    --control-plane {{ K8S_MASTER_NODE_IP }}:{{ K8S_API_SECURE_PORT }} --certificate-key {{ hostvars['K8S_TOKEN_HOLDER']['cert'] }}
  register: add_master
  #changed_when: '"This node has joined the cluster" in add_worker.stdout'